#!/usr/bin/env python3
"""
Compare Rust .dat output against C dsdgen Parquet reference.

Typical workflow:
    # 1. Obtain C dsdgen Parquet reference data, e.g. from datafusion-benchmarks:
    #    git clone https://github.com/apache/datafusion-benchmarks
    #    # the sf1 Parquet files are at datafusion-benchmarks/tpcds/data/sf1/

    # 2. Generate Rust output in C-compat mode:
    #    cargo run -p tpcdsgen -- --compat c --directory /tmp/tpcds-c

    # 3. Compare:
    #    uv run scripts/compare-c.py --dat-dir /tmp/tpcds-c --parquet-dir path/to/sf1 [TABLE...]

Usage:
    uv run scripts/compare-c.py --dat-dir DIR --parquet-dir DIR [TABLE...] [--verbose]
"""

import sys
import argparse
from decimal import Decimal
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq

SCRIPT_DIR = Path(__file__).parent.resolve()
sys.path.insert(0, str(SCRIPT_DIR))
from tpcds_schemas import all_schemas

MAX_DIFF_ROWS = 10  # Max differing rows to show per table


# ---------------------------------------------------------------------------
# Value normalization
# ---------------------------------------------------------------------------

def normalize_dat_value(raw: str, field: pa.Field):
    """Parse a raw .dat string into a typed, comparable Python value."""
    if raw == "":
        return None
    t = field.type
    if pa.types.is_integer(t):
        return int(raw)
    if pa.types.is_decimal(t):
        return Decimal(raw).normalize()
    if pa.types.is_date(t):
        return raw  # Keep as YYYY-MM-DD string
    return raw  # string: keep as-is (C dsdgen doesn't pad)


def fix_mojibake(s: str) -> str:
    """Fix strings where UTF-8 bytes were stored as individual Latin-1 characters.

    The C dsdgen Parquet reference was generated by tpcdsgen.py without
    specifying an encoding, so DataFusion read the raw UTF-8 bytes and stored
    each byte as a Latin-1 character. This re-encodes as Latin-1 then decodes
    as UTF-8, recovering the original Unicode string.
    """
    try:
        return s.encode("latin-1").decode("utf-8")
    except (UnicodeDecodeError, UnicodeEncodeError):
        return s


def normalize_parquet_value(scalar, field: pa.Field):
    """Normalize a pyarrow scalar into the same comparable Python value."""
    py = scalar.as_py()
    if py is None:
        return None
    t = field.type
    if pa.types.is_integer(t):
        return int(py)
    if pa.types.is_decimal(t):
        return Decimal(str(py)).normalize()
    if pa.types.is_date(t):
        return str(py)  # date → "YYYY-MM-DD"
    if pa.types.is_string(t) or pa.types.is_large_string(t):
        return fix_mojibake(py)
    return py


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------

def load_dat(table: str, fields: list[pa.Field], dat_dir: Path) -> list[tuple]:
    path = dat_dir / f"{table}.dat"
    if not path.exists():
        raise FileNotFoundError(
            f".dat file not found: {path}\n"
            f"Generate with: cargo run -p tpcdsgen -- --compat c --directory {dat_dir}"
        )

    rows = []
    with open(path, "r", encoding="latin-1") as f:
        for lineno, line in enumerate(f, 1):
            line = line.rstrip("\n")
            parts = line.split("|")
            # Drop trailing empty field produced by the trailing |
            if parts and parts[-1] == "":
                parts = parts[:-1]
            if len(parts) != len(fields):
                raise ValueError(
                    f"{table}.dat line {lineno}: expected {len(fields)} fields, "
                    f"got {len(parts)}: {line[:120]!r}"
                )
            rows.append(tuple(normalize_dat_value(p, fields[i]) for i, p in enumerate(parts)))
    return rows


def load_parquet(table: str, fields: list[pa.Field], parquet_dir: Path) -> list[tuple]:
    path = parquet_dir / f"{table}.parquet"
    if not path.exists():
        raise FileNotFoundError(f"Parquet reference not found: {path}")

    col_names = [f.name for f in fields]
    tbl = pq.read_table(path, columns=col_names)

    rows = []
    for batch in tbl.to_batches():
        for row_idx in range(batch.num_rows):
            rows.append(tuple(
                normalize_parquet_value(batch.column(i)[row_idx], fields[i])
                for i in range(len(fields))
            ))
    return rows


# ---------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------

def compare_table(table: str, verbose: bool, dat_dir: Path, parquet_dir: Path) -> bool:
    fields = all_schemas[table]
    col_names = [f.name for f in fields]

    try:
        dat_rows = load_dat(table, fields, dat_dir)
        pq_rows = load_parquet(table, fields, parquet_dir)
    except Exception as e:
        print(f"  ERROR: {e}")
        return False

    if len(dat_rows) != len(pq_rows):
        print(f"  ROW COUNT MISMATCH  rust={len(dat_rows)}  c={len(pq_rows)}")
        return False

    # Sort both by all columns for a canonical order.
    # This is O(n log n) but handles any ordering differences gracefully.
    dat_rows.sort(key=lambda r: tuple((v is None, v) if not isinstance(v, Decimal) else (False, float(v)) for v in r))
    pq_rows.sort(key=lambda r: tuple((v is None, v) if not isinstance(v, Decimal) else (False, float(v)) for v in r))

    diff_rows = 0
    first_diff_at = None
    for i, (dr, pr) in enumerate(zip(dat_rows, pq_rows)):
        if dr != pr:
            if diff_rows == 0:
                first_diff_at = i + 1
            diff_rows += 1
            if verbose and diff_rows <= MAX_DIFF_ROWS:
                print(f"  row {i+1}:")
                for j, (dv, pv) in enumerate(zip(dr, pr)):
                    if dv != pv:
                        print(f"    {col_names[j]}: rust={dv!r}  c={pv!r}")

    if diff_rows == 0:
        print(f"  \033[32m✓ MATCH\033[0m  {len(dat_rows)} rows")
        return True
    else:
        pct = 100.0 * diff_rows / len(dat_rows)
        print(f"  \033[31m✗ {diff_rows}/{len(dat_rows)} rows differ ({pct:.2f}%)  first diff at row {first_diff_at}\033[0m")
        if not verbose:
            print(f"    (re-run with --verbose to see column diffs)")
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Compare Rust .dat output vs C dsdgen Parquet reference")
    parser.add_argument("tables", nargs="*", help="Tables to compare (default: all)")
    parser.add_argument("--dat-dir", required=True,
                        help="Directory containing .dat files generated by: tpcdsgen --compat c --directory DIR")
    parser.add_argument("--parquet-dir", required=True,
                        help="Directory containing C dsdgen Parquet files (e.g. datafusion-benchmarks/tpcds/data/sf1)")
    parser.add_argument("--verbose", "-v", action="store_true", help="Show differing column values")
    args = parser.parse_args()

    dat_dir = Path(args.dat_dir)
    parquet_dir = Path(args.parquet_dir)

    available = sorted(all_schemas.keys())
    tables = args.tables if args.tables else available

    unknown = [t for t in tables if t not in all_schemas]
    if unknown:
        print(f"Unknown tables: {', '.join(unknown)}")
        print(f"Available: {', '.join(available)}")
        sys.exit(1)

    print(f"Comparing {len(tables)} table(s): Rust .dat  vs  C dsdgen Parquet\n")
    print(f"  dat-dir    : {dat_dir}")
    print(f"  parquet-dir: {parquet_dir}\n")

    results: dict[str, bool] = {}
    for table in tables:
        print(f"{table}:")
        results[table] = compare_table(table, args.verbose, dat_dir, parquet_dir)

    passed = [t for t, ok in results.items() if ok]
    failed = [t for t, ok in results.items() if not ok]

    print(f"\n{'='*50}")
    print(f"Passed : {len(passed)}/{len(results)}")
    if failed:
        print(f"Failed : {', '.join(failed)}")
    print("="*50)

    sys.exit(0 if not failed else 1)


if __name__ == "__main__":
    main()
