[package]
name = "tpchgen"
version = "0.1.0"
edition = "2021"
authors = ["clflushopt", "alamb"]

[dependencies]
chrono = "0.4.40"
indexmap = "2.7.1"
lazy_static = "1.5.0"

[dev-dependencies]
flate2 = "1.1.0"
