name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:  # Allow manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo-fmt
        run: cargo fmt --all -- --check
      - name: Run cargo-clippy
        run: cargo clippy -- -D warnings
      - name: Check
        run: cargo check --verbose --workspace --all-targets

  # Tests for tpchgen
  test-tests-tpchgen:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Tests (tpchgen)
        run: cargo test -p tpchgen --tests

  # doc examples test for tpchgen (takes a while)
  test-doc-tpchgen:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Doc Tests (tpchgen)
        run: cargo test -p tpchgen --doc

  # All tests for tpchgen-arrow
  test-all-tpchgen-arrow:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: All Tests (tpchgen-arrow)
        run: cargo test -p tpchgen-arrow

  # All tests for tpchgen-cli
  test-all-tpchgen-cli:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: All Tests (tpchgen-cli)
        run: cargo test -p tpchgen-cli


  # documentation build
  docs:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name : Build docs
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --no-deps --workspace


  # Conformance tests (compare to existing  implementation)
  conformance-test:
    name: TPC-H Conformance Tests
    runs-on: ubuntu-latest
    needs: [lint, test-tests-tpchgen, docs]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Make conformance script executable
        run: chmod +x ./tests/conformance.sh

      - name: Run Conformance Tests
        run: ./tests/conformance.sh